version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:13.5
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass@123
      POSTGRES_DB: test_db
    ports:
      - '5434:5432'
volumes:
  postgres:
